export const instituicoes = [
  { label: "UFCG", value: "UFCG" },
  { label: "UFPB", value: "UFPB" },
  { label: "IFPB", value: "IFPB" },
  { label: "USP", value: "USP" },
  { label: "SENAI", value: "SENAI" },
  { label: "Outra", value: "OUTRA" },
];

export const niveis = [
  { label: "Ensino Fundamental Incompleto", value: "FUNDAMENTAL_INCOMPLETO" },
  { label: "Ensino Fundamental Completo", value: "FUNDAMENTAL_COMPLETO" },
  { label: "Ensino Médio Incompleto", value: "MEDIO_INCOMPLETO" },
  { label: "Ensino Médio Completo", value: "MEDIO_COMPLETO" },
  { label: "Superior Incompleto", value: "SUPERIOR_INCOMPLETO" },
  { label: "Superior Completo", value: "SUPERIOR_COMPLETO" },
  { label: "Pós Graduação", value: "POS_GRADUACAO" },
];

export const interesses = [
  { label: "Inteligência Artificial", value: "IA" },
  { label: "Ciência de Dados", value: "CIENCIA_DE_DADOS" },
  { label: "Desenvolvimento Web", value: "DESENVOLVIMENTO_WEB" },
  { label: "Backend", value: "BACKEND" },
  { label: "Arquitetura de Software", value: "ARQUITETURA" },
  { label: "DevOps", value: "DEVOPS" },
  { label: "Infraestrutura", value: "INFRAESTRUTURA" },
  { label: "Suporte", value: "SUPORTE" },
  { label: "Suporte Técnico", value: "SUPORTE_TECNICO" },
  { label: "Frontend", value: "FRONTEND" },
  { label: "Mobile", value: "MOBILE" },
  { label: "Desenvolvimento de APIs", value: "DESENVOLVIMENTO_DE_APIS" },
  { label: "Microsserviços", value: "MICROSSERVICOS" },
  { label: "Sistemas Distribuídos", value: "SISTEMAS_DISTRIBUIDOS" },
  { label: "Qualidade de Software (QA)", value: "QA" },
  { label: "Testes Automatizados", value: "TESTES_AUTOMATIZADOS" },
  { label: "Engenharia de Requisitos", value: "ENGENHARIA_DE_REQUISITOS" },
  { label: "UX/UI Design", value: "UX_UI" },
  { label: "Produto (Product Management)", value: "PRODUTO" },
  { label: "Engenharia de Dados", value: "ENGENHARIA_DE_DADOS" },
  { label: "MLOps", value: "MLOPS" },
  { label: "NLP (Processamento de Linguagem Natural)", value: "NLP" },
  { label: "Visão Computacional", value: "VISAO_COMPUTACIONAL" },
  { label: "Sistemas de Recomendação", value: "SISTEMAS_DE_RECOMENDACAO" },
  { label: "Mineração de Dados", value: "MINERACAO_DE_DADOS" },
  { label: "Estatística Aplicada", value: "ESTATISTICA" },
  { label: "Business Intelligence (BI)", value: "BUSINESS_INTELLIGENCE" },
  { label: "Cibersegurança", value: "CIBERSEGURANCA" },
  { label: "Segurança de Aplicações", value: "SEGURANCA_DE_APLICACOES" },
  { label: "Redes e Protocolos", value: "REDES_E_PROTOCOLOS" },
  { label: "Cloud Computing", value: "CLOUD" },
  { label: "Pesquisa Científica (IC)", value: "PESQUISA_CIENTIFICA" },
  { label: "Inovação e Empreendedorismo", value: "EMPREENDEDORISMO" },
  { label: "Extensão Universitária", value: "EXTENSAO" },
  { label: "Monitoria", value: "MONITORIA" },
  { label: "Empresa Júnior", value: "EMPRESA_JUNIOR" },
  { label: "Hackathons e Competições", value: "HACKATHONS" },
  { label: "IoT (Internet das Coisas)", value: "IOT" },
  { label: "Robótica", value: "ROBOTICA" },
  { label: "Computação Gráfica", value: "COMPUTACAO_GRAFICA" },
  { label: "Jogos Digitais", value: "JOGOS" },
  { label: "Blockchain", value: "BLOCKCHAIN" },
  { label: "Sustentabilidade e Tech for Good", value: "SUSTENTABILIDADE" },
];

export const habilidades = [
  { label: "Java", value: "JAVA" },
  { label: "Spring", value: "SPRING" },
  { label: "JavaScript", value: "JAVASCRIPT" },
  { label: "React", value: "REACT" },
  { label: "Python", value: "PYTHON" },
  { label: "Machine Learning", value: "MACHINE_LEARNING" },
  { label: "Deep Learning", value: "DEEP_LEARNING" },
  { label: "SQL", value: "SQL" },
  { label: "PostgreSQL", value: "POSTGRESQL" },
  { label: "Docker", value: "DOCKER" },
  { label: "Git", value: "GIT" },
  { label: "Linux", value: "LINUX" },
  { label: "Windows", value: "WINDOWS" },
  { label: "Redes", value: "REDES" },
  { label: "Hardware", value: "HARDWARE" },
  { label: "TypeScript", value: "TYPESCRIPT" },
  { label: "C", value: "C" },
  { label: "C++", value: "CPP" },
  { label: "C#", value: "CSHARP" },
  { label: "Go", value: "GO" },
  { label: "Rust", value: "RUST" },
  { label: "Kotlin", value: "KOTLIN" },
  { label: "Swift", value: "SWIFT" },
  { label: "PHP", value: "PHP" },
  { label: "R", value: "R" },
  { label: "Next.js", value: "NEXTJS" },
  { label: "Node.js", value: "NODEJS" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "Tailwind CSS", value: "TAILWIND" },
  { label: "React Native", value: "REACT_NATIVE" },
  { label: "Flutter", value: "FLUTTER" },
  { label: "Spring Boot", value: "SPRING_BOOT" },
  { label: "REST APIs", value: "REST" },
  { label: "GraphQL", value: "GRAPHQL" },
  { label: "Microsserviços", value: "MICROSSERVICOS" },
  { label: "Mensageria (Kafka/RabbitMQ)", value: "MENSAGERIA" },
  { label: "MySQL", value: "MYSQL" },
  { label: "SQLite", value: "SQLITE" },
  { label: "MongoDB", value: "MONGODB" },
  { label: "Redis", value: "REDIS" },
  { label: "Modelagem de Dados", value: "MODELAGEM_DE_DADOS" },
  { label: "ETL/ELT", value: "ETL_ELT" },
  { label: "Pandas", value: "PANDAS" },
  { label: "NumPy", value: "NUMPY" },
  { label: "Scikit-learn", value: "SCIKIT_LEARN" },
  { label: "TensorFlow", value: "TENSORFLOW" },
  { label: "PyTorch", value: "PYTORCH" },
  { label: "NLP", value: "NLP" },
  { label: "Visão Computacional", value: "VISAO_COMPUTACIONAL" },
  { label: "LLMs / Prompt Engineering", value: "LLMS_PROMPT_ENGINEERING" },
  { label: "Avaliação de Modelos (métricas)", value: "AVALIACAO_DE_MODELOS" },
  { label: "Docker Compose", value: "DOCKER_COMPOSE" },
  { label: "Kubernetes", value: "KUBERNETES" },
  { label: "CI/CD", value: "CI_CD" },
  { label: "GitHub Actions", value: "GITHUB_ACTIONS" },
  { label: "GitLab CI", value: "GITLAB_CI" },
  { label: "AWS", value: "AWS" },
  { label: "GCP", value: "GCP" },
  { label: "Azure", value: "AZURE" },
  { label: "Terraform", value: "TERRAFORM" },
  { label: "Testes Unitários", value: "TESTES_UNITARIOS" },
  { label: "Testes de Integração", value: "TESTES_DE_INTEGRACAO" },
  { label: "TDD", value: "TDD" },
  {
    label: "Observabilidade (Logs/Métricas/Tracing)",
    value: "OBSERVABILIDADE",
  },
  { label: "Segurança (OWASP)", value: "SEGURANCA_OWASP" },
  { label: "Figma", value: "FIGMA" },
  { label: "Scrum", value: "SCRUM" },
  { label: "Kanban", value: "KANBAN" },
  { label: "Comunicação", value: "COMUNICACAO" },
  { label: "Trabalho em Equipe", value: "TRABALHO_EM_EQUIPE" },
  { label: "Inglês", value: "INGLES" },
  { label: "Escrita Científica", value: "ESCRITA_CIENTIFICA" },
  { label: "Apresentação", value: "APRESENTACAO" },
];

export const publicoAlvo = [
  { label: "Alunos de graduação", value: "ALUNO_GRADUACAO" },
  { label: "Alunos de pós graduação", value: "ALUNO_POS_GRADUACAO" },
  { label: "Técnicos", value: "TECNICO" },
  { label: "Pesquisadores", value: "PESQUISADOR" },
];

export const categorias = [
  { label: "Projeto de Pesquisa", value: "PROJETO_PESQUISA" },
  {
    label: "Projeto de Pesquisa e Desenvolvimento",
    value: "PROJETO_PESQUISA_DESENVOLVIMENTO",
  },
  {
    label: "Projeto de Pesquisa, Desenvolvimento e Inovação",
    value: "PROJETO_PESQUISA_DESENVOLVIMENTO_INOVACAO",
  },
  { label: "Projeto de Extensão", value: "PROJETO_EXTENSAO" },
  { label: "Monitoria", value: "MONITORIA" },
  { label: "Organização de Evento", value: "ORGANIZACAO_EVENTO" },
  { label: "Outros", value: "OUTROS" },
];

export const tipoPerfil = [
  { label: "Candidato", value: "CANDIDATO" },
  { label: "Recrutador", value: "RECRUTADOR" },
];

export const cargoCandidato = [
  { label: "Aluno", value: "ALUNO" },
  { label: "Técnico Administrativo", value: "TECNICO" },
];

export const cargaHoraria = [
  { label: "Até 10h", value: "ATE_10H" },
  { label: "De 10 a 20h", value: "DE_10_A_20H" },
  { label: "De 20 a 30h", value: "DE_20_A_30H" },
  { label: "Acima de 30h", value: "ACIMA_DE_30H" },
];

export const simNao = [
  { label: "Sim", value: true },
  { label: "Não", value: false },
];
export const cargosRecrutador = [
  { label: "Professor", value: "PROFESSOR" },
  { label: "Pesquisador", value: "PESQUISADOR" },
  { label: "Técnico", value: "TECNICO" },
];

export const cargosCandidato = [
  { label: "Aluno", value: "ALUNO" },
  { label: "Técnico", value: "TECNICO" },
];
